// Generated by nuxi
/// <reference types="@nuxtjs/eslint-module" />
/// <reference types="@nuxtjs/dotenv" />
/// <reference types="@nuxtjs/html-validator" />
/// <reference types="@nuxtjs/svg" />
/// <reference types="@nuxt/bridge-edge" />
/// <reference types="bootstrap-vue" />
/// <reference types="@nuxtjs/axios" />
/// <reference types="@nuxtjs/auth-next" />
/// <reference types="vue-social-sharing" />
/// <reference types="nuxt-clipboard" />
/// <reference types="@nuxtjs/recaptcha" />
/// <reference types="@nuxt/components" />
/// <reference types="@nuxt/telemetry" />

export {}
